[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
SpacePhysicsMakie = "0c28ffd8-ae30-4a56-b2e4-f8332c621ad2"
Speasy = "09b745ad-c67d-442f-94a6-c7f4d1e4d861"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
